# Generated by Django 4.2.5 on 2023-12-03 18:56

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("buildings", "0001_initial"),
        ("taggit", "0005_auto_20220424_2025"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="")),
                ("end_date", models.DateTimeField(db_index=True, verbose_name="")),
                ("description", models.TextField(verbose_name="")),
                (
                    "ages",
                    models.CharField(
                        choices=[
                            ("0+", "0+"),
                            ("6+", "6+"),
                            ("12+", "12+"),
                            ("14+", "14+"),
                            ("16+", "16+"),
                            ("18+", "18+"),
                        ],
                        default="0+",
                        max_length=3,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="apps/events/static/img", verbose_name=""
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=255,
                        unique=True,
                        verbose_name="url мероприятия",
                    ),
                ),
                ("people_count", models.IntegerField(default=0)),
                ("booked_balcony", models.IntegerField(default=0)),
                ("booked_sitting", models.IntegerField(default=0)),
                ("booked_dance_floor", models.IntegerField(default=0)),
                (
                    "filter",
                    models.CharField(
                        choices=[
                            ("all", "all"),
                            ("sport", "sport"),
                            ("concerts", "concerts"),
                            ("festivals", "festivals"),
                            ("kids", "kids"),
                        ],
                        default="all",
                        max_length=50,
                    ),
                ),
                (
                    "genre",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event",
                        to="buildings.area",
                    ),
                ),
            ],
            options={
                "verbose_name": "событие",
                "verbose_name_plural": "События",
                "db_table": "events",
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField(default=0)),
                (
                    "spot",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sitting", "sitting"),
                            ("balcony", "balcony"),
                            ("dance_floor", "dance_floor"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "билет",
                "verbose_name_plural": "Билеты",
            },
        ),
        migrations.CreateModel(
            name="Booked_Places",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "spot",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sitting", "sitting"),
                            ("balcony", "balcony"),
                            ("dance_floor", "dance_floor"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("spot_num", models.IntegerField(default=0)),
                ("available", models.BooleanField(default=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="available",
                        to="events.event",
                    ),
                ),
            ],
        ),
    ]
