# Generated by Django 4.2.6 on 2023-12-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="booked_places",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
