# Generated by Django 4.2.5 on 2023-12-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booked_places",
            name="spot_row",
            field=models.IntegerField(default=0),
        ),
    ]
