# Generated by Django 4.2.5 on 2023-12-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="booked_balcony",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="event",
            name="booked_dance_floor",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="event",
            name="booked_sitting",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="spot",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sitting", "sitting"),
                    ("balcony", "balcony"),
                    ("dance_floor", "dance_floor"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
