# Generated by Django 4.2.5 on 2023-12-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_event_booked_balcony_event_booked_dance_floor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="spot_num",
            field=models.IntegerField(default=0),
        ),
    ]
