# Generated by Django 4.2.6 on 2023-12-18 10:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_delete_booked_places"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="rows",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), default=[], size=None
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="spot",
            field=models.CharField(
                blank=True,
                choices=[
                    ("seat", "seat"),
                    ("balcony", "balcony"),
                    ("dance_floor", "dance_floor"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
