# Generated by Django 4.2.5 on 2023-12-03 14:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_ticket_spot_num"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="spot_num",
        ),
    ]
