# Generated by Django 4.2.5 on 2023-12-03 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_remove_ticket_spot_num"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booked_Places",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "spot",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sitting", "sitting"),
                            ("balcony", "balcony"),
                            ("dance_floor", "dance_floor"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("spot_num", models.IntegerField(default=0)),
                ("available", models.BooleanField(default=True)),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="available",
                        to="events.event",
                    ),
                ),
            ],
        ),
    ]
