# Generated by Django 4.2.6 on 2023-12-18 11:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_ticket_rows_alter_ticket_spot"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="booked_sitting",
            new_name="booked_seat",
        ),
    ]
