# Generated by Django 4.2.5 on 2023-12-03 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_booked_places"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booked_places",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="available",
                to="events.event",
            ),
        ),
    ]
