# Generated by Django 4.2.5 on 2023-11-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0006_remove_tickets_events_tickets_event_tickets_price_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tickets",
            new_name="Ticket",
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateTimeField(db_index=True, verbose_name=""),
        ),
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, unique=True, verbose_name="url мероприятия"
            ),
        ),
    ]
