# Generated by Django 4.2.5 on 2023-11-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0008_event_place"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="filter",
            field=models.CharField(
                choices=[
                    ("all", "all"),
                    ("sport", "sport"),
                    ("concert", "concert"),
                    ("festival", "festival"),
                    ("kids", "kids"),
                ],
                default="all",
                max_length=50,
            ),
        ),
    ]
