# Generated by Django 5.0 on 2023-12-09 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("address", models.CharField(default="", max_length=2000)),
                ("map_adress", models.CharField(default="", max_length=2000)),
            ],
            options={
                "db_table": "building",
            },
        ),
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("has_balcony", models.BooleanField(default=False)),
                ("has_sitting", models.BooleanField(default=False)),
                ("has_dance_floor", models.BooleanField(default=False)),
                ("capacity_balcony", models.IntegerField(default=0)),
                ("capacity_sitting", models.IntegerField(default=0)),
                ("capacity_dance_floor", models.IntegerField(default=0)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="area",
                        to="buildings.building",
                    ),
                ),
            ],
            options={
                "db_table": "areas",
            },
        ),
    ]
