# Generated by Django 5.0 on 2023-12-09 17:50

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("buildings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="area",
            name="capacity_balcony",
        ),
        migrations.RemoveField(
            model_name="area",
            name="capacity_dance_floor",
        ),
        migrations.RemoveField(
            model_name="area",
            name="capacity_sitting",
        ),
        migrations.AddField(
            model_name="area",
            name="capacity",
            field=django.contrib.postgres.fields.hstore.HStoreField(
                default="сидячие-13"
            ),
            preserve_default=False,
        ),
    ]
