# Generated by Django 4.2.5 on 2023-12-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buildings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="has_balcony",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="area",
            name="has_dance_floor",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="area",
            name="has_sitting",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="building",
            name="map_adress",
            field=models.CharField(default="", max_length=2000),
        ),
    ]
