# Generated by Django 4.2.5 on 2023-12-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buildings", "0002_area_has_balcony_area_has_dance_floor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="booked_balcony",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="area",
            name="booked_dance_floor",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="area",
            name="booked_sitting",
            field=models.IntegerField(default=0),
        ),
    ]
