# Generated by Django 4.2.5 on 2023-12-03 14:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("buildings", "0003_area_booked_balcony_area_booked_dance_floor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="area",
            name="booked_balcony",
        ),
        migrations.RemoveField(
            model_name="area",
            name="booked_dance_floor",
        ),
        migrations.RemoveField(
            model_name="area",
            name="booked_sitting",
        ),
    ]
