# Generated by Django 4.2.5 on 2023-12-03 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_time", models.DateTimeField(blank=True, null=True)),
                ("spot_num", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "объект",
                "verbose_name_plural": "Покупки",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=32, null=True)),
                ("second_name", models.CharField(max_length=32, null=True)),
                ("gender", models.CharField(max_length=9)),
                ("birth_date", models.DateField(null=True)),
                ("balance", models.FloatField(default=0)),
                ("bonus", models.FloatField(default=0)),
                ("buyback_sum", models.FloatField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "профиль пользователя",
                "verbose_name_plural": "Профили пользователей",
                "db_table": "Users",
            },
        ),
    ]
