# Generated by Django 4.2.6 on 2023-12-13 14:44

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(blank=True, null=True)),
                ('spot_num', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'объект',
                'verbose_name_plural': 'Покупки',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=32)),
                ('second_name', models.CharField(blank=True, default='', max_length=32)),
                ('gender', models.CharField(blank=True, default='', max_length=9)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('balance', models.FloatField(default=0)),
                ('bonus', models.FloatField(default=0)),
                ('buyback_sum', models.FloatField(default=0)),
                ('basket', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=''), blank=True, null=True, size=None)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'db_table': 'Users',
            },
        ),
    ]
