# Generated by Django 4.2.6 on 2023-12-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="spot_row",
            field=models.IntegerField(default=0),
        ),
    ]
