# Generated by Django 4.2.5 on 2023-11-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="age",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="balance",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="bonus",
            field=models.FloatField(default=0),
        ),
    ]
