# Generated by Django 4.2.5 on 2023-12-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_remove_purchase_basket_alter_userprofile_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="spot_num",
            field=models.IntegerField(default=0),
        ),
    ]
