# Generated by Django 4.2.5 on 2023-10-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_userprofile_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="birth_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="first_name",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                choices=[("F", "Female"), ("M", "Male"), ("undefined", "undefined")],
                default="undefined",
                max_length=9,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="second_name",
            field=models.CharField(max_length=32, null=True),
        ),
    ]
