# Generated by Django 4.2.5 on 2023-11-04 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0007_rename_tickets_ticket_alter_event_date_and_more"),
        ("accounts", "0005_alter_userprofile_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("buyback_sum", models.FloatField(default=0)),
                (
                    "tickets",
                    models.ManyToManyField(blank=True, null=True, to="events.ticket"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="accounts.userprofile",
                    ),
                ),
            ],
        ),
    ]
