# Generated by Django 4.2.5 on 2023-11-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_purchase_delete_purchasehistory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchase",
            old_name="tickets",
            new_name="ticket",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="buyback_sum",
            field=models.FloatField(default=0),
        ),
    ]
